server:
  port: 9000
spring:
  r2dbc:
    url: r2dbc:postgresql://10.106.100.54:5432/bus_zgt?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: bus_zgt
    password: dev_jakx8Uydq
    name: r2dbc
    pool:
      enabled: false #开启连接池（暂时不要开启连接池，超过后会阻塞）
      validation-query: SELECT 1
      initial-size: 2 #初始连接数，默认10
      max-idle-time: 30 #允许连接在池中处于空闲状态的最长时间。
      max-life-time: 9999 #池中连接的最大生存期。默认情况下，连接具有无限的生命
      max-acquire-time: 9999 #从池中获取连接的最长时间。默认情况下，等待无限期
      max-validation-time: 9999 # 从池中验证连接的最长时间。默认情况下，等待无限期
      maxCreateConnectionTime: 9999 #创建新连接的最长等待时间。默认情况下，无限期等待。
      max-size: 2 #最大连接池大小,默认10

#加载mapper的sql-xml文件
mybatis:
  mapper-locations: classpath*:mybatis/*.xml
#  config-location: classpath:/mybatis/mybatis-config.xml
#type-aliases-package: com.riskeys.channel.**.entity

# LOGGING
logging:
  level:
    root: INFO
    com.wendel: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.data.r2dbc: DEBUG
    org.apache.ibatis.r2dbc: DEBUG